export enum TaxSystem {
  SINGLE_TAX_GROUP_2 = 'SINGLE_TAX_GROUP_2',
  SINGLE_TAX_GROUP_3_5 = 'SINGLE_TAX_GROUP_3_5',
  SINGLE_TAX_GROUP_3_3 = 'SINGLE_TAX_GROUP_3_3',
  GENERAL_SYSTEM = 'GENERAL_SYSTEM',
}
